// ============================================================
// SANKET — Core Type Definitions
// System for Anomaly & Network Knowledge Extraction from Transactions
// ============================================================

/**
 * Risk levels used throughout the system for investigative alerts,
 * transactions, and entity assessments.
 */
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * System operational status — SANKET is always offline/local.
 */
export type SystemStatusType = 'OFFLINE' | 'READY' | 'PROCESSING' | 'ERROR';

/**
 * Represents an evidence item attached to an alert or investigation.
 * Mirrors the backend ApiEvidenceItem shape.
 */
export interface EvidenceItem {
  category: string;
  description: string;
  confidence: number;
  source: string;
}

/**
 * Component scores from the scoring engine.
 *
 * Backend canonical keys (authoritative):
 *   M  = Multivariate Anomaly
 *   T  = Temporal
 *   N  = Network
 *   G  = Graph
 *   S  = Structural
 *   Gs = Graph Support
 *   C  = Confidence
 *
 * Index signature allows any key for forward-compatibility.
 */
export interface ComponentScores {
  [key: string]: number;
}

/**
 * Confidence breakdown for scoring transparency.
 *
 * Backend canonical keys (authoritative):
 *   D  = Data Completeness
 *   E  = Evidence Agreement
 *   S  = Statistical Stability
 *   Gs = Graph Support
 *   X  = Explanation Consistency
 *
 * Index signature allows any key for forward-compatibility.
 */
export interface ConfidenceComponents {
  [key: string]: number;
}

/**
 * Investigative alert — a prioritized, ranked lead generated by
 * the detection engine. Mirrors backend AlertSummaryResponse.
 * Not a declaration of criminal activity.
 */
export interface Alert {
  alert_id: string;
  transaction_id: string;
  rank: number;
  risk_score: number;
  confidence_score: number;
  risk_level: RiskLevel;
  priority_score: number;
  triggered_detectors: string[];
  independent_signal_count: number;
  evidence_items: EvidenceItem[];
  evidence_categories: string[];
  component_scores: ComponentScores;
  scoring_version: string;
  /** Optional: present in mock data but not in backend API response */
  created_at?: string;
}

/**
 * A full investigation object — the deep-dive analysis result
 * for a specific transaction.
 */
export interface InvestigationObject {
  transaction_id: string;
  risk_score: number;
  confidence_score: number;
  risk_level: RiskLevel;
  triggered_detectors: string[];
  detector_scores: Record<string, number>;
  evidence_items: EvidenceItem[];
  evidence_categories: string[];
  independent_signal_count: number;
  data_quality: number;
  component_scores: ComponentScores;
  confidence_components: ConfidenceComponents;
  cross_category_agreement: number;
  scoring_version: string;
  graph_evidence: Record<string, unknown>;
}

/**
 * A node in the transaction/entity graph.
 *
 * Backend canonical node_type values (authoritative):
 *   TRANSACTION | ADDRESS | IP | ASN | COUNTRY | CANDIDATE_ENTITY
 *
 * NOTE: Former mock values ('address', 'transaction', 'entity', 'cluster')
 * are NOT valid backend values and must NOT be used in API calls.
 */
export interface GraphNode {
  node_id: string;
  node_type: 'TRANSACTION' | 'ADDRESS' | 'IP' | 'ASN' | 'COUNTRY' | 'CANDIDATE_ENTITY';
  attributes: Record<string, unknown>;
}

/**
 * An edge in the transaction/entity graph.
 *
 * Backend canonical edge_type values (authoritative):
 *   INPUT_TO | OUTPUT_TO | OBSERVED_WITH | SAME_IP | SAME_ASN |
 *   TEMPORALLY_ASSOCIATED | CANDIDATE_SAME_ENTITY
 *
 * NOTE: Former mock values ('input', 'output', 'transfer', 'association')
 * are NOT valid backend values and must NOT be used in API calls.
 */
export interface GraphEdge {
  edge_id: string;
  source_id: string;
  target_id: string;
  edge_type:
    | 'INPUT_TO'
    | 'OUTPUT_TO'
    | 'OBSERVED_WITH'
    | 'SAME_IP'
    | 'SAME_ASN'
    | 'TEMPORALLY_ASSOCIATED'
    | 'CANDIDATE_SAME_ENTITY';
  timestamp: number | null;
  attributes: Record<string, unknown>;
  metadata: Record<string, unknown>;
}

/**
 * Navigation item for the sidebar.
 */
export interface NavItem {
  label: string;
  href: string;
  icon: string;
  description: string;
  section?: 'main' | 'system';
}

/**
 * Page metadata for placeholder pages.
 */
export interface PageMeta {
  title: string;
  description: string;
  icon: string;
}

/**
 * Analysis run status.
 */
export type StatusType = 'completed' | 'processing' | 'failed' | 'queued';

/**
 * Analysis run record.
 * Mapped from GET /api/v1/run/latest for real data.
 */
export interface AnalysisRun {
  run_id: string;
  dataset_name: string;
  status: StatusType;
  started_at: string;
  completed_at?: string;
  transaction_count: number;
  alert_count: number;
  scoring_version: string;
}

/**
 * Transaction record for the forensic investigation console.
 * Derived from GET /api/v1/transactions/{txid} canonical_transaction field.
 */
export interface TransactionRecord {
  txid: string;
  timestamp: string;
  block_height: number;
  value_btc: number;
  fee_btc: number;
  inputs_count: number;
  outputs_count: number;
  risk_score: number;
  risk_level: RiskLevel;
  confidence: number;
  triggered_detectors: string[];
  observed_ip?: string;
  observed_asn?: string;
  status: 'confirmed' | 'anomalous' | 'flagged';
}

/**
 * Candidate entity heuristic grouping.
 * NOTE: The backend does NOT expose a dedicated entity endpoint yet.
 * This type is retained for the entities page which currently shows
 * mock data with a clear notice.
 */
export interface CandidateEntity {
  entity_id: string;
  label: string;
  heuristic_method: string;
  address_count: number;
  total_volume_btc: number;
  associated_alerts_count: number;
  risk_assessment: RiskLevel;
  first_seen: string;
  last_seen: string;
  confidence: number;
  sample_addresses: string[];
  supporting_evidence: string[];
}

/**
 * Re-export current-run context types for convenient access across the app.
 */
export type { CompactRunMetadata, RunLifecycleStatus, RunContextValue } from '@/context/RunContext';
