// ============================================================
// SANKET — Core Type Definitions
// System for Anomaly & Network Knowledge Extraction from Transactions
// ============================================================

/**
 * Risk levels used throughout the system for investigative alerts,
 * transactions, and entity assessments.
 */
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * System operational status — SANKET is always offline/local.
 */
export type SystemStatusType = 'OFFLINE' | 'READY' | 'PROCESSING' | 'ERROR';

/**
 * Represents an evidence item attached to an alert or investigation.
 */
export interface EvidenceItem {
  category: string;
  description: string;
  confidence: number;
  source: string;
}

/**
 * Component scores from the scoring engine.
 */
export interface ComponentScores {
  structural: number;
  temporal: number;
  behavioral: number;
  network: number;
  [key: string]: number;
}

/**
 * Confidence breakdown for scoring transparency.
 */
export interface ConfidenceComponents {
  data_coverage: number;
  signal_agreement: number;
  model_confidence: number;
  [key: string]: number;
}

/**
 * Investigative alert — a prioritized, ranked lead generated by
 * the detection engine. Not a declaration of criminal activity.
 */
export interface Alert {
  alert_id: string;
  transaction_id: string;
  rank: number;
  risk_score: number;
  confidence_score: number;
  risk_level: RiskLevel;
  priority_score: number;
  triggered_detectors: string[];
  independent_signal_count: number;
  evidence_items: EvidenceItem[];
  evidence_categories: string[];
  component_scores: ComponentScores;
  scoring_version: string;
  created_at?: string;
}

/**
 * A full investigation object — the deep-dive analysis result
 * for a specific transaction.
 */
export interface InvestigationObject {
  transaction_id: string;
  risk_score: number;
  confidence_score: number;
  risk_level: RiskLevel;
  triggered_detectors: string[];
  detector_scores: Record<string, number>;
  evidence_items: EvidenceItem[];
  evidence_categories: string[];
  independent_signal_count: number;
  data_quality: number;
  component_scores: ComponentScores;
  confidence_components: ConfidenceComponents;
  cross_category_agreement: number;
  scoring_version: string;
  graph_evidence: Record<string, unknown>;
}

/**
 * A node in the transaction/entity graph.
 */
export interface GraphNode {
  node_id: string;
  node_type: 'address' | 'transaction' | 'entity' | 'cluster';
  attributes: Record<string, unknown>;
}

/**
 * An edge in the transaction/entity graph.
 */
export interface GraphEdge {
  source_id: string;
  target_id: string;
  edge_type: 'input' | 'output' | 'transfer' | 'association';
  timestamp: string;
  attributes: Record<string, unknown>;
}

/**
 * Navigation item for the sidebar.
 */
export interface NavItem {
  label: string;
  href: string;
  icon: string;
  description: string;
  section?: 'main' | 'system';
}

/**
 * Page metadata for placeholder pages.
 */
export interface PageMeta {
  title: string;
  description: string;
  icon: string;
}

/**
 * Analysis run status.
 */
export type StatusType = 'completed' | 'processing' | 'failed' | 'queued';

/**
 * Analysis run record.
 */
export interface AnalysisRun {
  run_id: string;
  dataset_name: string;
  status: StatusType;
  started_at: string;
  completed_at?: string;
  transaction_count: number;
  alert_count: number;
  scoring_version: string;
}

/**
 * Transaction record for the forensic investigation console.
 */
export interface TransactionRecord {
  txid: string;
  timestamp: string;
  block_height: number;
  value_btc: number;
  fee_btc: number;
  inputs_count: number;
  outputs_count: number;
  risk_score: number;
  risk_level: RiskLevel;
  confidence: number;
  triggered_detectors: string[];
  observed_ip?: string;
  observed_asn?: string;
  status: 'confirmed' | 'anomalous' | 'flagged';
}

/**
 * Candidate entity heuristic grouping.
 */
export interface CandidateEntity {
  entity_id: string;
  label: string;
  heuristic_method: string;
  address_count: number;
  total_volume_btc: number;
  associated_alerts_count: number;
  risk_assessment: RiskLevel;
  first_seen: string;
  last_seen: string;
  confidence: number;
  sample_addresses: string[];
  supporting_evidence: string[];
}
