'use client';

import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  useCallback,
  useMemo,
} from 'react';

// ============================================================
// SANKET — Current Run Context (Track 1 / A1)
// Authoritative frontend state tracking the active analysis run.
// Strictly holds compact metadata. No large alert/tx/graph arrays.
// ============================================================

export type RunLifecycleStatus = 'idle' | 'running' | 'completed' | 'failed';

export interface CompactRunMetadata {
  /** Authoritative unique run identifier generated by the backend */
  run_id: string;
  /** Run lifecycle state */
  lifecycle: RunLifecycleStatus;
  /** Pipeline version string (e.g. "0.1.0") */
  pipeline_version?: string;
  /** Total records in the ingested dataset */
  record_count?: number;
  /** Count of rejected/invalid rows */
  rejected_record_count?: number;
  /** Total alerts generated by the scoring engine */
  alert_count?: number;
  /** Dataset metadata (e.g. filename, size) without raw record contents */
  dataset_metadata?: Record<string, unknown>;
  /** Stage timings in seconds */
  execution_timings?: Record<string, number>;
  /** Compact execution metrics */
  execution_metrics?: Record<string, unknown>;
  /** High-level graph topology summary (counts only) */
  graph_summary?: Record<string, unknown>;
  /** Pipeline execution warnings */
  warnings?: string[];
  /** Pipeline execution errors */
  errors?: string[];
  /** Timestamp when analysis started */
  started_at?: string;
  /** Timestamp when analysis completed */
  completed_at?: string;
}

export interface RunContextValue {
  /** Authoritative active run ID, null if no run has executed */
  runId: string | null;
  /** Current run lifecycle state */
  lifecycle: RunLifecycleStatus;
  /** Compact run metadata, null if no run is loaded */
  currentRun: CompactRunMetadata | null;
  /** Whether the context has hydrated from client sessionStorage */
  isHydrated: boolean;
  /** Initiate a run tracking state */
  startRun: (datasetName?: string) => void;
  /** Record a completed run with compact backend metadata */
  completeRun: (metadata: Omit<CompactRunMetadata, 'lifecycle'>) => void;
  /** Record a failed run with error detail */
  failRun: (errorMessage?: string) => void;
  /** Reset / clear active run state */
  clearRun: () => void;
}

const SESSION_STORAGE_KEY = 'sanket_current_run';

/**
 * Extracts strictly compact run-level metadata from backend analysis output,
 * stripping out large arrays (ranked_alerts, raw data, etc.).
 */
export function toCompactRunMetadata(
  res: {
    run_id: string;
    pipeline_version?: string;
    record_count?: number;
    rejected_record_count?: number;
    ranked_alerts?: unknown[];
    dataset_metadata?: Record<string, unknown>;
    execution_timings?: Record<string, number>;
    execution_metrics?: Record<string, unknown>;
    graph_summary?: Record<string, unknown>;
    warnings?: string[];
    errors?: string[];
  },
  startedAt?: string
): Omit<CompactRunMetadata, 'lifecycle'> {
  return {
    run_id: res.run_id,
    pipeline_version: res.pipeline_version,
    record_count: res.record_count,
    rejected_record_count: res.rejected_record_count,
    alert_count: Array.isArray(res.ranked_alerts) ? res.ranked_alerts.length : 0,
    dataset_metadata: res.dataset_metadata,
    execution_timings: res.execution_timings,
    execution_metrics: res.execution_metrics,
    graph_summary: res.graph_summary,
    warnings: res.warnings,
    errors: res.errors,
    started_at: startedAt,
    completed_at: new Date().toISOString(),
  };
}

function loadInitialRun(): CompactRunMetadata | null {
  if (typeof window === 'undefined') return null;
  try {
    const raw = window.sessionStorage.getItem(SESSION_STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed.run_id === 'string' && parsed.run_id.trim() !== '') {
      return parsed as CompactRunMetadata;
    }
  } catch (err) {
    console.warn('[RunContext] Failed to parse current run from sessionStorage:', err);
  }
  return null;
}

function persistRun(data: CompactRunMetadata | null): void {
  if (typeof window === 'undefined') return;
  try {
    if (data) {
      window.sessionStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify(data));
    } else {
      window.sessionStorage.removeItem(SESSION_STORAGE_KEY);
    }
  } catch (err) {
    console.warn('[RunContext] Failed to persist current run to sessionStorage:', err);
  }
}

const RunContext = createContext<RunContextValue | null>(null);

export function RunProvider({ children }: { children: React.ReactNode }) {
  const [currentRun, setCurrentRun] = useState<CompactRunMetadata | null>(null);
  const [isHydrated, setIsHydrated] = useState(false);

  // Hydrate from sessionStorage once mounted on client
  useEffect(() => {
    const saved = loadInitialRun();
    if (saved) {
      setCurrentRun(saved);
    }
    setIsHydrated(true);
  }, []);

  // Sync back to sessionStorage when state changes after initial hydration
  useEffect(() => {
    if (!isHydrated) return;
    persistRun(currentRun);
  }, [currentRun, isHydrated]);

  const startRun = useCallback((datasetName?: string) => {
    setCurrentRun({
      run_id: '',
      lifecycle: 'running',
      dataset_metadata: datasetName ? { filename: datasetName } : undefined,
      started_at: new Date().toISOString(),
    });
  }, []);

  const completeRun = useCallback((metadata: Omit<CompactRunMetadata, 'lifecycle'>) => {
    const compact: CompactRunMetadata = {
      ...metadata,
      lifecycle: 'completed',
      completed_at: metadata.completed_at || new Date().toISOString(),
    };
    setCurrentRun(compact);
  }, []);

  const failRun = useCallback((errorMessage?: string) => {
    setCurrentRun((prev) => {
      const existingErrors = prev?.errors || [];
      return {
        run_id: prev?.run_id || '',
        lifecycle: 'failed',
        dataset_metadata: prev?.dataset_metadata,
        started_at: prev?.started_at,
        completed_at: new Date().toISOString(),
        errors: errorMessage ? [...existingErrors, errorMessage] : existingErrors,
      };
    });
  }, []);

  const clearRun = useCallback(() => {
    setCurrentRun(null);
  }, []);

  const value = useMemo<RunContextValue>(() => ({
    runId: currentRun?.run_id ? currentRun.run_id : null,
    lifecycle: currentRun?.lifecycle || 'idle',
    currentRun,
    isHydrated,
    startRun,
    completeRun,
    failRun,
    clearRun,
  }), [currentRun, isHydrated, startRun, completeRun, failRun, clearRun]);

  return (
    <RunContext.Provider value={value}>
      {children}
    </RunContext.Provider>
  );
}

export function useCurrentRun(): RunContextValue {
  const context = useContext(RunContext);
  if (!context) {
    throw new Error('useCurrentRun must be used within a RunProvider');
  }
  return context;
}

export const useRun = useCurrentRun;
